//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ОООТехносервис.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBVakulenkoRequests413Entities : DbContext
    {
        public DBVakulenkoRequests413Entities()
            : base("name=DBVakulenkoRequests413Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<Priority> Priority { get; set; }
        public virtual DbSet<Problem> Problem { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Stage> Stage { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Request_View> Request_View { get; set; }
        public virtual DbSet<GroupProblem> GroupProblem { get; set; }
    
        public virtual ObjectResult<GetRequestMasterName_Result> GetRequestMasterName(string nameMaster)
        {
            var nameMasterParameter = nameMaster != null ?
                new ObjectParameter("NameMaster", nameMaster) :
                new ObjectParameter("NameMaster", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRequestMasterName_Result>("GetRequestMasterName", nameMasterParameter);
        }
    
        public virtual ObjectResult<GetRequestMasterShortName_Result> GetRequestMasterShortName(string masterName)
        {
            var masterNameParameter = masterName != null ?
                new ObjectParameter("MasterName", masterName) :
                new ObjectParameter("MasterName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRequestMasterShortName_Result>("GetRequestMasterShortName", masterNameParameter);
        }
    }
}
